### ISSUE TITLE
Can't go through validate hook with an pkrvars file as input

### ISSUE THREAD

**Issue by schniber** [cisagov/pre-commit-packer#3]
# 💡 Summary #

It would be great to allow the args to specify the path to the pkrvars file to be used when validating the packer files

## Motivation and context ##

as of today the basic command with packer works : 
packer validate -var-file="inputs/dev.pkrvars.hcl" .  

However when using the pre-commit hook validate there is no way to map with the righ pkrvars file.
This would be useful because...

## Implementation notes ##

Please provide details for implementation, such as:

an example would be : 

repos:
  - repo: https://github.com/cisagov/pre-commit-packer
    rev: v0.0.2
    hooks:
      - id: packer_fmt
      - id: packer_validate
        args:
          - '--args=--var-file="inputs/dev.pkrvars.hcl'

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Ability to run validate by providing a pkrvars.hcl file as input

**Comment by h3ct0rjs** [comment]
Hi, I'm currently writing a few pipelines and I would like to use this pre-commit option, I'm just wondering if this is implemented  @mcdonnnj ?

I will check if I can add this to the code, but it will take me a while.

**Comment by mcdonnnj** [comment]
As of the [0.1.0 release](https://github.com/cisagov/pre-commit-packer/releases/tag/v0.1.0) you should be able to do this with:

```yaml
repo: https://github.com/cisagov/pre-commit-packer
rev: v0.2.0
hooks:
  - id: packer_fmt
  - id: packer_validate
    args:
      - '-var-file=inputs/dev.pkrvars.hcl"'
```
