### ISSUE TITLE
[BUG] - Arrays are not defined and validated in script execution

### ISSUE THREAD

**Issue by jared-bloomer** [cisagov/pre-commit-packer#60]
# 🐛 Summary #

@ARGS and @FILES arrays are not initialized of checked properly in the `packer_fmt.sh` and `packer_validate.sh` scripts. 

## To reproduce ##

1. Use the following configuration in your .pre-commit-config.yaml
```
- repo: https://github.com/cisagov/pre-commit-packer
    rev: v0.3.0
    hooks:
      - id: packer_fmt
      - id: packer_validate
```
1. Commit a valid .pkr.hcl file to execute the pre-commits

## Expected behavior ##

Scripts execute and perform the intended checks

## Any helpful log output or screenshots ##

What I have personally Experienced is 

```
Packer Format............................................................Failed
- hook id: packer_fmt
- exit code: 1

/Users/my-username/.cache/pre-commit/repozsjgy0qa/hooks/packer_fmt.sh: line 23: ARGS[@]: unbound variable

Packer Validate..........................................................Failed
- hook id: packer_validate
- exit code: 1

/Users/my-username/.cache/pre-commit/repozsjgy0qa/hooks/packer_validate.sh: line 28: ARGS[@]: unbound variable
```

However, I can run `packer validate .` and get `The configuration is valid.` and I can also run `packer fmt .` and get an exit code of 0. 

Reviewing the Scripts I am not seeing `ARGS[@]` or `FILES[@]` being initialized. I am also not seeing proper validation checks of `ARGS[@]`. What I mean by this is 

```
for file in "${FILES[@]}"; do
  if ! packer fmt "${ARGS[@]}" -- "$file"; then
    error=1
    echo
    echo "Failed path: $file"
    echo "================================"
  fi
done
``` 

should actually be wrapped in an additional `if` statement. 

```
for file in "${FILES[@]}"; do
  if [ ${#ARGS[@]} -gt 0 ]; then
    if ! packer fmt "${ARGS[@]}" -- "$file"; then
      error=1
      echo
      echo "Failed path: $file"
      echo "================================"
    fi
  else:
    if ! packer fmt  -- "$file"; then
      error=1
      echo
      echo "Failed path: $file"
      echo "================================"
    fi
  fi
done
```

With the current version, passing arguments in .pre-commit-comfig.yaml is required. The configuration I am having to use right now to make this version work is

```
- repo: https://github.com/cisagov/pre-commit-packer
    rev: v0.3.0
    hooks:
      - id: packer_fmt
        args:
          - --check
      - id: packer_validate
        args:
          - --except=foo
```
